# set path=%path%;C:\Program Files\MATLAB_R2018b_x64\bin\win64
LIBS = libmx.lib libmex.lib
LIBPATH = /LIBPATH:"C:\Program Files\MATLAB_R2018b_x64\extern\lib\win64\microsoft"

all:
	cl /nologo /W3 /I "C:\Program Files\MATLAB\R2018b\simulink\include" /I "C:\Program Files\MATLAB\R2018b\extern\include" timesTwo.c